### ISSUE TITLE
Changing color when releasing finger

### ISSUE THREAD

**Issue by Silvia4** [naturaln0va/RAScrollablePickerView#1]
Hi!
I really like your work, but I've found some little problems. For example, when I release the finger from the screen the colors change a lot. Also they don't distribute evenly in the view (the yellow is completely missing in this position):

![simulator screen shot - iphone 8 - 2018-05-30 at 12 56 18](https://user-images.githubusercontent.com/38463563/40716318-df09053e-6408-11e8-8122-1ea73a0f2747.png)

PS: yes, I want to use only the hue slider and in vertical position.

Thanks a lot!

**Comment by naturaln0va** [comment]
Hello, I'm glad you are enjoying this control!

The reason that the view continues to update after you let go is because the value decelerates to based on how fast you were swiping the view. I added an option to remove this if you'd like in this commit: https://github.com/naturaln0va/RAScrollablePickerView/commit/496bf8b6389f3d69da2c10bea6468f166e0796fa. 

Also there is some limitations in the way the gradient is drawn. I added 2 more control points to the picker's gradient. You should be able to see some yellow now. This was address in this commit: https://github.com/naturaln0va/RAScrollablePickerView/commit/71c5c9d8e65ccd45ac09354ed4eec6954a62fc0a.

![screen shot 2018-05-30 at 7 32 52 am](https://user-images.githubusercontent.com/8561621/40720309-ec17024e-63db-11e8-9cad-e83c10d0d2e9.png)
